// @generated by scriptify/generate-types.ts from schema/*.json
// DO NOT EDIT - run `npm run build:types` to regenerate.

export interface Notice {
/**
 * Producer identifier. Top-level for self-contained subsystems; colon-namespaced for parameterized producers such as `provider:openai` or `exec:search`.
 */
source: string
/**
 * Open discriminator within a source. Examples include `grammar_unenforced`, `embed_progress`, `search_progress`, and `turn_awaiting_model`.
 */
kind: string
/**
 * Display severity set by the producer. It does not make the Notice a durable operation result.
 */
level: ("error" | "warn" | "info")
/**
 * Optional terse, factual display message.
 */
message?: (string | null)
/**
 * Optional typed position for an observation. ContentOffset points into model output; LogCoordinate points at a durable log row without replacing it.
 */
position?: (ContentOffset | LogCoordinate | null)
[k: string]: unknown
}

export interface ContentOffset {
type: "content-offset"
line: number
column: number
}

export interface LogCoordinate {
type: "log-coordinate"
/**
 * Log row identity, typically `log:///<loop>/<turn>/<sequence>`.
 */
coordinate: string
/**
 * Optional op token (FIND/READ/EDIT/...) at the coordinate, for human-readable rendering.
 */
op?: string
}

export type OperationResult = ({
status: number
problem?: ProblemDetails
error?: never
[k: string]: unknown
} & {
status?: number
})

/**
 * PLURNK operation failure using RFC 9457 Problem Details. Extension members are permitted so an owning boundary can add structured causal and recovery facts without inventing a second error envelope.
 */

export interface ProblemDetails {
/**
 * Absolute URI identifying the stable problem class.
 */
type: string
/**
 * Short, stable summary for this problem type.
 */
title: string
/**
 * Operation status. It must equal the containing result status.
 */
status: number
/**
 * Specific, causal explanation of this occurrence.
 */
detail: string
/**
 * Absolute URI identifying the failed durable operation, normally its log URI. Core adds it at persistence when a plugin cannot know the durable coordinate.
 */
instance?: string
/**
 * Stable producer-owned stage at which the operation failed, when the operation has multiple independently recoverable stages.
 */
stage?: string
/**
 * One generally valid next action. It is omitted when recovery depends on facts the producer does not know.
 */
recovery?: string
/**
 * Whether the producer recommends automatically retrying the identical request.
 */
retryable?: boolean
[k: string]: unknown
}
