// @generated by scriptify/generate-types.ts from schema/*.json
// DO NOT EDIT — run `npm run build:types` to regenerate.

export type Disposition = ({
posture: ("native" | "generic")
dimensions: Dimensions
evidence: Evidence
} | {
posture: "unsupported"
reason: string
dimensions: Dimensions
evidence: Evidence
})
/**
 * @minItems 1
 */

export type Dimensions = [("admission" | "projection" | "framing" | "success" | "failure" | "lifecycle" | "durability" | "composition" | "presentation"), ...(("admission" | "projection" | "framing" | "success" | "failure" | "lifecycle" | "durability" | "composition" | "presentation"))[]]
/**
 * @minItems 1
 */

export type Evidence = [string, ...(string)[]]

/**
 * One client's exhaustive, evidence-bearing disposition for an installed AG-UI discovery surface.
 */

export interface AguiClientConformance {
schemaVersion: 1
client: string
actions: {
[k: string]: Disposition
}
notifications: {
[k: string]: Disposition
}
}

export type Name = string

/**
 * Language-neutral raw SSE and AG-UI lifecycle specimens consumed by every Plurnk client.
 */

export interface AguiConformanceKit {
schemaVersion: 1
/**
 * @minItems 1
 */
transport: [TransportSpecimen, ...(TransportSpecimen)[]]
/**
 * @minItems 1
 */
lifecycles: [LifecycleSpecimen, ...(LifecycleSpecimen)[]]
}

export interface TransportSpecimen {
name: Name
/**
 * @minItems 1
 */
chunks: [string, ...(string)[]]
eof: boolean
expect: ({
events: Event[]
} | {
error: "invalid-json"
})
}

export interface Event {
type: string
[k: string]: unknown
}

export interface LifecycleSpecimen {
name: Name
/**
 * @minItems 1
 */
events: [Event, ...(Event)[]]
expect: LifecycleExpectation
}

export interface LifecycleExpectation {
completion: ("success" | "interrupt" | "error" | "dead-stream")
families: string[]
status?: number
interrupt?: ("proposal" | "interaction")
action?: ActionExpectation
}

export interface ActionExpectation {
kind: string
ok: boolean
status?: number
}

export type ClientDisplayCapabilities = (SchemeDisplayCapability | MimetypeDisplayCapability)[]

/**
 * The complete installed AG-UI+ management and notification surface. Action and notification names are object keys so identity has one representation.
 */

export interface AguiDiscovery {
schemaVersion: 1
actions: {
[k: string]: Action
}
notifications: {
[k: string]: Notification
}
display: ClientDisplayCapabilities
}

export interface Action {
scope: ("worldless" | "workspace")
inputSchema: JsonSchema
outputSchema: JsonSchema
}
/**
 * A JSON Schema 2020-12 schema supplied by the contract owner.
 */

export interface JsonSchema {
[k: string]: unknown
}

export interface Notification {
payloadSchema: JsonSchema
}

export interface SchemeDisplayCapability {
kind: "scheme"
scheme: string
display: CapabilityDisplay
}

export interface CapabilityDisplay {
glyph?: string
}

export interface MimetypeDisplayCapability {
kind: "mimetype"
mimetype: string
display: CapabilityDisplay
}

export interface ClientInteractionProjection {
interactionId: number
workerId: number
loopId: number
turnId: number
request: ClientInteractionRequest
}
/**
 * A runtime-neutral request for one client-owned interaction. The owner supplies the standard tool presentation and response contract; protocol-private continuation state is excluded.
 */

export interface ClientInteractionRequest {
toolName: string
arguments: {
[k: string]: unknown
}
message?: string
responseSchema: {
[k: string]: unknown
}
}

export type ClientInteractionResolution = ({
status: "resolved"
payload?: unknown
} | {
status: "cancelled"
})

export type ClientStatement = (PlurnkStatement | LookStatement | BuffStatement)
/**
 * The parsed AST union for one protocol statement, discriminated by `op`. Every variant has fixed signal, target, lineMarker, annotation, body, delimiter, and source-position fields; operation-specific schemas constrain their types. A null field records an omitted tolerated slot and does not satisfy runtime requirements by itself.
 */

export type PlurnkStatement = (FindStatement | ReadStatement | OpenStatement | FoldStatement | EditStatement | CopyStatement | MoveStatement | SendStatement | ExecStatement | BareStatement | WorkStatement | ForkStatement | KillStatement | PlanStatement)
/**
 * A parsed target slot from a plurnk statement. Discriminated on `kind`: a bare local path or a WHATWG-decomposed URL. Targets carry an exact address or a path glob; content matching belongs in the statement body.
 */

export type ParsedPath = (LocalPath | UrlPath)
/**
 * Parsed body of a FIND/OPEN/FOLD statement, discriminated on `dialect`. The dialect is determined by the body's leading characters (`//` xpath, `/` regex, `$` jsonpath, `~` semantic, `@` graph, else glob). The regex variant carries pattern and flags split out of the `/pattern/flags` literal; every variant remains JSON-serializable.
 */

export type MatcherBody = (XPathBody | RegexBody | JsonPathBody | SemanticBody | GraphBody | GlobBody)

export type AnnotationOrNull = (string | null)

export type TagSignal = (string[] | null)

export type PathOrNull = (ParsedPath | null)

export type TextLineMarkerOrNull = (TextLineMarker | null)

export type MatcherBodyOrNull = (MatcherBody | null)

export type LineMarkerOrNull = (LineMarker | null)

export interface FindStatement {
op: "FIND"
delimiter: string
annotation: (string | null)
signal: (string[] | null)
target: (ParsedPath | null)
lineMarker: (LineMarker | null)
body: (MatcherBody | null)
position: Position
}
/**
 * A bare local path with no `scheme://` prefix. The raw string is stored verbatim; resolution is the runtime's job.
 */

export interface LocalPath {
kind: "local"
raw: string
}
/**
 * A path with a `scheme://` prefix, fully decomposed via WHATWG URL.
 */

export interface UrlPath {
kind: "url"
raw: string
scheme: string
username: (string | null)
password: (string | null)
hostname: (string | null)
port: (number | null)
pathname: string
/**
 * Canonical serialized WHATWG query component without the leading `?`. Null means no query; the empty string means an explicit empty query (`?`). Ordering, duplicate names, and encoded spelling are preserved.
 */
query: (string | null)
fragment: (string | null)
/**
 * Trailing `{key: value}` request-metadata blocks removed before WHATWG decomposition and preserved as ordered pairs. Order and duplicate names survive; the addressed scheme owns their meaning. Absent when no block was supplied.
 */
headers?: [string, string][]
}
/**
 * The ordered numeric components parsed from a `<scope>` slot. AstBuilder converts each lexical number to a JavaScript number; the operation owner assigns arity and meaning, including text coordinates, result positions, timing, mutation anchors, and an optional leading semantic threshold.
 */

export interface LineMarker {
/**
 * @minItems 1
 */
marks: [number, ...(number)[]]
}
/**
 * XPath 1.0 expression. Validated at parse time via the xpath library.
 */

export interface XPathBody {
dialect: "xpath"
raw: string
}
/**
 * ECMAScript regex literal `/pattern/flags`. Escape a literal delimiter as `\/`. Pattern and flags are split out for direct use. `raw` preserves the literal form for round-tripping.
 */

export interface RegexBody {
dialect: "regex"
raw: string
pattern: string
flags: string
}
/**
 * RFC 9535 JSONPath expression. Compiled at parse time with json-p3, the same engine used for runtime matching.
 */

export interface JsonPathBody {
dialect: "jsonpath"
raw: string
}
/**
 * Semantic similarity query. Body is `~phrase`: natural language after the tilde, with no parse step. Similarity thresholds and result ranges belong to the statement's scope; resolution happens service-side through the configured embedding implementation.
 */

export interface SemanticBody {
dialect: "semantic"
raw: string
}
/**
 * Code-graph reference query. Body is `@symbol` for a neighborhood, `@<symbol` for inbound references, or `@>symbol` for outbound references. Resolution happens service-side through the symbol index; no parse step occurs in the language parser.
 */

export interface GraphBody {
dialect: "graph"
raw: string
}
/**
 * Pattern with no dialect prefix; treated as a glob/literal match.
 */

export interface GlobBody {
dialect: "glob"
raw: string
}
/**
 * A source point in parsed PLURNK input. Lines are 1-based; columns are 0-based Unicode code points. LF and CRLF delimit lines, while a lone CR occupies one column. The exact pair {line: 0, column: 0} is the sole unknown/degraded position.
 */

export interface Position {
line: number
column: number
}

export interface ReadStatement {
op: "READ"
delimiter: string
annotation: (string | null)
signal: (string[] | null)
target: (ParsedPath | null)
lineMarker: (TextLineMarker | null)
body: null
position: Position
}
/**
 * The ordered components parsed from a text-coordinate <scope>. A line position may be numeric or a rendered five-character Base62 line anchor; columns remain numeric. Core resolves anchors against the addressed current text before a numeric scope reaches its operation owner.
 */

export interface TextLineMarker {
/**
 * @minItems 1
 */
marks: [(number | string), ...((number | string))[]]
}

export interface OpenStatement {
op: "OPEN"
delimiter: string
annotation: (string | null)
signal: (string[] | null)
target: (ParsedPath | null)
lineMarker: (TextLineMarker | null)
body: (MatcherBody | null)
position: Position
}

export interface FoldStatement {
op: "FOLD"
delimiter: string
annotation: (string | null)
signal: (string[] | null)
target: (ParsedPath | null)
lineMarker: (TextLineMarker | null)
body: (MatcherBody | null)
position: Position
}

export interface EditStatement {
op: "EDIT"
delimiter: string
annotation: (string | null)
signal: (string[] | null)
target: (ParsedPath | null)
lineMarker: (TextLineMarker | null)
body: (string | null)
position: Position
}

export interface CopyStatement {
op: "COPY"
delimiter: string
annotation: (string | null)
signal: (string[] | null)
target: (ParsedPath | null)
lineMarker: (TextLineMarker | null)
body: (ResourceSelection | null)
position: Position
}
/**
 * A COPY/MOVE destination target and optional text scope. A target without a fragment selects the scheme's default channel; a fragment selects a named channel; lineMarker scopes the selected destination content.
 */

export interface ResourceSelection {
target: ParsedPath
lineMarker: (TextLineMarker | null)
}

export interface MoveStatement {
op: "MOVE"
delimiter: string
annotation: (string | null)
signal: (string[] | null)
target: (ParsedPath | null)
lineMarker: (TextLineMarker | null)
body: (ResourceSelection | null)
position: Position
}

export interface SendStatement {
op: "SEND"
delimiter: string
annotation: (string | null)
signal: (number | null)
target: (ParsedPath | null)
lineMarker: (LineMarker | null)
body: (SendBody | null)
position: Position
}
/**
 * Parsed body of a SEND statement. `raw` is the literal body text; `json` is the best-effort `JSON.parse(raw)` result, or null when the body isn't valid JSON.
 */

export interface SendBody {
raw: string
json: unknown
}

export interface ExecStatement {
op: "EXEC"
delimiter: string
annotation: (string | null)
signal: (string | null)
target: (ParsedPath | null)
lineMarker: (LineMarker | null)
body: (string | null)
position: Position
}

export interface BareStatement {
op: "BARE"
delimiter: string
annotation: (string | null)
signal: (string[] | null)
target: null
lineMarker: null
body: string
position: Position
}

export interface WorkStatement {
op: "WORK"
delimiter: string
annotation: (string | null)
signal: (string | null)
target: (ParsedPath | null)
lineMarker: null
body: string
position: Position
}

export interface ForkStatement {
op: "FORK"
delimiter: string
annotation: (string | null)
signal: (string | null)
target: (ParsedPath | null)
lineMarker: null
body: string
position: Position
}

export interface KillStatement {
op: "KILL"
delimiter: string
annotation: (string | null)
signal: (number | null)
target: (ParsedPath | null)
lineMarker: null
body: (string | null)
position: Position
}

export interface PlanStatement {
op: "PLAN"
delimiter: string
annotation: (string | null)
signal: (string[] | null)
target: (ParsedPath | null)
lineMarker: (LineMarker | null)
body: (string | null)
position: Position
}

export interface LookStatement {
op: "LOOK"
delimiter: string
annotation: AnnotationOrNull
signal: TagSignal
target: PathOrNull
lineMarker: TextLineMarkerOrNull
body: MatcherBodyOrNull
position: Position
}

export interface BuffStatement {
op: "BUFF"
delimiter: string
annotation: AnnotationOrNull
signal: TagSignal
target: PathOrNull
lineMarker: LineMarkerOrNull
body: MatcherBodyOrNull
position: Position
}

export type EntryReadResult = ({
status: 200
entry: ClientEntry
} | {
status: number
problem: ProblemDetails
entry: null
})

export interface ClientEntry {
entryId: number
target: string
channels: {
[k: string]: ClientEntryChannel
}
}

export interface ClientEntryChannel {
content: string
contentOffset: number
contentLength: number
mimetype: string
weight: number
state: ("static" | "active" | "closed" | "errored")
}
/**
 * PLURNK operation failure using RFC 9457 Problem Details. Extension members are permitted so an owning boundary can add structured causal and recovery facts without inventing a second error envelope.
 */

export interface ProblemDetails {
/**
 * Absolute URI identifying the stable problem class.
 */
type: string
/**
 * Short, stable summary for this problem type.
 */
title: string
/**
 * Operation status. It must equal the containing result status.
 */
status: number
/**
 * Specific, causal explanation of this occurrence.
 */
detail: string
/**
 * Absolute URI identifying the failed durable operation, normally its log URI. Core adds it at persistence when a plugin cannot know the durable coordinate.
 */
instance?: string
/**
 * Stable producer-owned stage at which the operation failed, when the operation has multiple independently recoverable stages.
 */
stage?: string
/**
 * One generally valid next action. It is omitted when recovery depends on facts the producer does not know.
 */
recovery?: string
/**
 * Whether the producer recommends automatically retrying the identical request.
 */
retryable?: boolean
[k: string]: unknown
}

export interface LoopFlags {
mode: ("ask" | "act")
auto: boolean
noWeb: boolean
noInteraction: boolean
noProposals: boolean
}

export interface McpConfigurationOverlay {
[k: string]: string
}

export type McpServerDefinition = ({
[k: string]: unknown
} & {
name: string
transport: ("stdio" | "http")
command?: string
args?: string[]
cwd?: string
env?: {
[k: string]: string
}
url?: string
headers?: {
[k: string]: string
}
authorization?: ({
type: "bearer"
token: EnvironmentReference
} | {
type: "oauth"
redirectUrl: string
clientMetadataUrl: string
scope?: string
} | {
type: "oauth"
redirectUrl: string
clientId: string
clientSecret: EnvironmentReference
scope?: string
} | {
type: "oauth"
redirectUrl: string
scope?: string
} | {
type: "client-credentials"
clientId: string
clientSecret: EnvironmentReference
scope?: string
issuer?: string
})
tools?: string[]
read?: string[]
})

export type EnvironmentReference = string

export type McpServerArguments = string[]

export type McpServerAuthorization = ({
type: "bearer"
token: string
} | {
type: "oauth"
redirectUrl: string
clientMetadataUrl: string
scope?: string
} | {
type: "oauth"
redirectUrl: string
clientId: string
clientSecret: string
scope?: string
} | {
type: "oauth"
redirectUrl: string
scope?: string
} | {
type: "client-credentials"
clientId: string
clientSecret: string
scope?: string
issuer?: string
})

export type McpServerToolNames = string[]

export type McpServerReadTools = string[]

export interface McpServerOptions {
args?: McpServerArguments
cwd?: string
env?: McpServerEnvironment
headers?: McpServerHeaders
authorization?: McpServerAuthorization
tools?: McpServerToolNames
read?: McpServerReadTools
}

export interface McpServerEnvironment {
[k: string]: string
}

export interface McpServerHeaders {
[k: string]: string
}

export interface ModelCatalogPage {
/**
 * @maxItems 100
 */
items: ModelCatalogEntry[]
offset: number
total: number
nextOffset?: number
}

export interface ModelCatalogEntry {
selector: string
provider: string
providerName: string
model: string
modelName: string
limits: ModelCatalogLimits
capabilities: ModelCatalogCapabilities
readiness: ModelReadiness
}

export interface ModelCatalogLimits {
contextTokens: number
inputTokens?: number
outputTokens?: number
}

export interface ModelCatalogCapabilities {
attachment: boolean
reasoning: boolean
toolCall: boolean
structuredOutput?: boolean
temperature?: boolean
inputModalities: string[]
outputModalities: string[]
}
/**
 * Local configuration evidence that a catalog provider is ready to attempt a request, without probing or validating credentials.
 */

export interface ModelReadiness {
ready: boolean
causes: ModelReadinessCause[]
}

export interface ModelReadinessCause {
kind: ("credential" | "configuration")
/**
 * Alternative environment-variable sets. Every name in one inner array is required; satisfying any inner array resolves this cause.
 *
 * @minItems 1
 */
alternatives: [[string, ...(string)[]], ...([string, ...(string)[]])[]]
}

export interface ModelCatalogQuery {
provider?: string
search?: string
availability?: ("configured" | "all")
offset?: number
limit?: number
}

export interface ModelRoute {
alias?: string
provider: string
model: string
}

export interface Notice {
/**
 * Producer identifier. Top-level for self-contained subsystems; colon-namespaced for parameterized producers such as `provider:openai` or `exec:search`.
 */
source: string
/**
 * Open discriminator within a source. Examples include `grammar_unenforced`, `embed_progress`, `search_progress`, and `turn_awaiting_model`.
 */
kind: string
/**
 * Display severity set by the producer. It does not make the Notice a durable operation result.
 */
level: ("error" | "warn" | "info")
/**
 * Optional terse, factual display message.
 */
message?: (string | null)
/**
 * Optional typed position for an observation. ContentOffset points into model output; LogCoordinate points at a durable log row without replacing it.
 */
position?: (ContentOffset | LogCoordinate | null)
[k: string]: unknown
}
/**
 * A point in model output using the parser-point convention: 1-based line and 0-based Unicode-code-point column. Absence or a null Notice.position represents an unknown location.
 */

export interface ContentOffset {
type: "content-offset"
line: number
column: number
}

export interface LogCoordinate {
type: "log-coordinate"
/**
 * Log row identity, typically `log:///<loop>/<turn>/<sequence>`.
 */
coordinate: string
/**
 * Optional op token (FIND/READ/EDIT/...) at the coordinate, for human-readable rendering.
 */
op?: string
}

export type OperationResult = ({
status: number
problem?: ProblemDetails
range?: RangeExtent
error?: never
[k: string]: unknown
} & {
status?: number
})
/**
 * @minItems 2
 * @maxItems 2
 */

export type RequestedRange = [number, number]
/**
 * @minItems 2
 * @maxItems 2
 */

export type ReturnedRange = [number, number]

/**
 * PLURNK operation failure using RFC 9457 Problem Details. Extension members are permitted so an owning boundary can add structured causal and recovery facts without inventing a second error envelope.
 */

export interface RangeExtent {
unit: ("line" | "result" | "resource" | "matchLocation")
total: number
requested: RequestedRange
returned?: ReturnedRange
}

export type AppliedTagSignal = (string[] | null)

export type CurationTagSignal = (string[] | null)

export type ResourceSelectionOrNull = (ResourceSelection | null)

export type SendBodyOrNull = (SendBody | null)

export type ProposalDisposition = ({
owner: "client"
} | {
owner: "loop"
decision: ("accept" | "reject")
outcome?: string
})

export interface ProposalProjection {
logEntryId: number
workerId: number
loopId: number
turnId: number
op: ("FIND" | "READ" | "EDIT" | "COPY" | "MOVE" | "OPEN" | "FOLD" | "SEND" | "EXEC" | "BARE" | "WORK" | "FORK" | "KILL" | "PLAN")
target: {
scheme: (string | null)
pathname: (string | null)
}
body: string
attrs: {
[k: string]: unknown
}
flags: LoopFlags
staleClobberRisk: boolean
disposition: ProposalDisposition
}
/**
 * The complete effective policy posture of one model loop. Persisted partial objects are expanded to this shape by the runtime owner before use or projection.
 */

export type ProviderCost = ({
kind: "charged"
amount: MonetaryAmount
usdEquivalent?: string
source: string
} | {
kind: "estimated"
amount: MonetaryAmount
source: string
} | {
kind: "unknown"
reason: string
})

/**
 * Ordered physical provider-request evidence and its deterministic aggregate projection.
 */

export interface ProviderAccounting {
requests: ProviderRequestAccounting[]
usage: (ProviderUsage | null)
costUsd: (string | null)
}
/**
 * The normalized accounting disposition of one physical provider request.
 */

export interface ProviderRequestAccounting {
provider: string
model: string
outcome: ("response" | "error")
status?: number
usage?: ProviderUsage
cost: ProviderCost
}
/**
 * Known token quantities for one provider request. Omitted fields are unknown; explicit zero is observed or exactly derived.
 */

export interface ProviderUsage {
inputTokens?: number
outputTokens?: number
totalTokens?: number
inputTokenDetails?: {
noCacheTokens?: number
cacheReadTokens?: number
cacheWriteTokens?: number
}
outputTokenDetails?: {
textTokens?: number
reasoningTokens?: number
}
}

export interface MonetaryAmount {
amount: string
currency: string
}

export type DecimalAmount = string

export type NonEmptyString = string

export type Tokens = number

/**
 * Known token quantities for one provider request. Omitted fields are unknown; explicit zero is observed or exactly derived.
 */

export type ReasoningPolicy = ("off" | "adaptive" | "low" | "medium" | "high")

export interface TextRegion {
startLine: number
startColumn: number
endLine: number
endColumn: number
}
