// @generated by scriptify/generate-types.ts from schema/*.json
// DO NOT EDIT — run `npm run build:types` to regenerate.

export interface ChannelContent {
/**
 * Raw content bytes/string for this channel. Binary content awaits a future encoding pass (see AGENTS.md).
 */
content: string
mimetype: string
/**
 * Token count of `content` under the active model's tokenizer.
 */
tokens: number
}

export type ClientStatement = (PlurnkStatement | LookStatement | BuffStatement)
/**
 * The parsed AST of one plurnk statement. Discriminated on `op`. OPEN, FOLD, KILL, WORK, and FORK have no `<L>` slot (`lineMarker` is always null for those); WORK and FORK carry an optional single Git branch ref in `signal`; SEND's `<L>` slot carries an optional terminal wait scope (runtime semantics admit it on [202]; null on mid-comms SENDs); EXEC's `<L>` slot carries an optional `<timeout,poll>`. `target` is the URI of the operand (parsed into ParsedPath structure); null when the operand slot was omitted. Body shape varies per op: matcher dialect for FIND/READ/OPEN/FOLD, raw string for EDIT/EXEC, ResourceSelection for COPY/MOVE destinations, SendBody for SEND, opaque annotation string for KILL (no assigned runtime meaning; lands in the log), reasoning text for PLAN (recorded to the log; no other effect), and a required prompt string for WORK (spawn a fresh named worker) and FORK (branch the current worker into a named sibling). The `worker://<name>` in target names the new worker.
 */

export type PlurnkStatement = (FindStatement | ReadStatement | OpenStatement | FoldStatement | EditStatement | CopyStatement | MoveStatement | SendStatement | ExecStatement | WorkStatement | ForkStatement | KillStatement | PlanStatement)
/**
 * A parsed path slot from a plurnk statement. Discriminated on `kind`: a bare local path (no scheme) or a fully decomposed URL. Paths address exact resources or carry shell glob selectors; content matching belongs in the statement body.
 */

export type ParsedPath = (LocalPath | UrlPath)
/**
 * Parsed body of a FIND/READ/OPEN/FOLD statement, discriminated on `dialect`. The dialect is determined by the body's leading characters (`//` xpath, `/` regex, `$` jsonpath, `~` semantic, `@` graph, else glob). The regex variant carries pattern/flags split out of the `/pattern/flags` literal; the compiled `RegExp` object on the in-memory AST is a runtime ergonomic only and is not part of the persisted/wire contract.
 */

export type MatcherBody = (XPathBody | RegexBody | JsonPathBody | SemanticBody | GraphBody | GlobBody)

export type TagSignal = (string[] | null)

export type PathOrNull = (ParsedPath | null)

export type LineMarkerOrNull = (LineMarker | null)

export type MatcherBodyOrNull = (MatcherBody | null)

export interface FindStatement {
op: "FIND"
suffix: string
signal: (string[] | null)
target: (ParsedPath | null)
lineMarker: (LineMarker | null)
body: (MatcherBody | null)
position: Position
}
/**
 * A bare local path with no `scheme://` prefix. The raw string is stored verbatim; resolution is the runtime's job.
 */

export interface LocalPath {
kind: "local"
raw: string
}
/**
 * A path with a `scheme://` prefix, fully decomposed via WHATWG URL.
 */

export interface UrlPath {
kind: "url"
raw: string
scheme: string
username: (string | null)
password: (string | null)
hostname: (string | null)
port: (number | null)
pathname: string
params: Params
fragment: (string | null)
/**
 * Request-metadata blocks split off the target — trailing `{key: value}` groups (e.g. `(https://api{Authorization: Bearer x})`). Ordered key/value pairs so order and duplicate names survive; opaque to the grammar's addressing, interpreted by the scheme handler (auth, content-type, method affordance). Absent when the target carries no `{...}` block. See #46.
 */
headers?: [string, string][]
}
/**
 * URL query parameters parsed into a JSON object. Single-value keys map to strings; multi-value keys (repeated in the original query string) map to arrays of strings. Empty object when the URL has no query string; nullable usages wrap this schema in a oneOf with null.
 */

export interface Params {
[k: string]: (string | string[])
}
/**
 * A parsed `<L>` slot: the ordered numeric components, verbatim. Signed integers may carry runtime sentinel meaning (0 = prepend anchor, -1 = append anchor); a leading decimal may be a semantic similarity threshold. Arity is interpretation, owned by the consumer: `[N]` = one position; `[N, M]` = a range; four integers = an exact text region; `[0.7, 10, 20]` = a thresholded range (score >= 0.7, positions 10-20). The grammar carries the numbers; it does not assign them roles.
 */

export interface LineMarker {
/**
 * @minItems 1
 */
marks: [number, ...(number)[]]
}
/**
 * XPath 1.0 expression. Validated at parse time via the xpath library.
 */

export interface XPathBody {
dialect: "xpath"
raw: string
}
/**
 * ECMAScript regex literal `/pattern/flags`. Escape a literal delimiter as `\/`. Pattern and flags are split out for direct use. `raw` preserves the literal form for round-tripping.
 */

export interface RegexBody {
dialect: "regex"
raw: string
pattern: string
flags: string
}
/**
 * JSONPath expression. Validated at parse time via jsonpath-plus.
 */

export interface JsonPathBody {
dialect: "jsonpath"
raw: string
}
/**
 * Semantic similarity query. Body is `~phrase` — natural language after the tilde, no parse step. Resolution happens service-side via the deep-embed channel; omitted `<Result>` uses the consumer's default count, while an explicit value narrows the results.
 */

export interface SemanticBody {
dialect: "semantic"
raw: string
}
/**
 * Code-graph reference query. Body is `@symbol` (neighborhood — both inbound and outbound edges), `@<symbol` (inbound — who references this), or `@>symbol` (outbound — what this references). Resolution happens service-side via a deep-graph channel; no parse step in grammar.
 */

export interface GraphBody {
dialect: "graph"
raw: string
}
/**
 * Pattern with no dialect prefix; treated as a glob/literal match.
 */

export interface GlobBody {
dialect: "glob"
raw: string
}
/**
 * A line/column position in a parsed plurnk document. ANTLR emits 1-based lines and 0-based columns; degraded positions may use 0 for both when the source token's location is unknown.
 */

export interface Position {
line: number
column: number
}

export interface ReadStatement {
op: "READ"
suffix: string
signal: (string[] | null)
target: (ParsedPath | null)
lineMarker: (LineMarker | null)
body: (MatcherBody | null)
position: Position
}

export interface OpenStatement {
op: "OPEN"
suffix: string
signal: (string[] | null)
target: (ParsedPath | null)
lineMarker: null
body: (MatcherBody | null)
position: Position
}

export interface FoldStatement {
op: "FOLD"
suffix: string
signal: (string[] | null)
target: (ParsedPath | null)
lineMarker: null
body: (MatcherBody | null)
position: Position
}

export interface EditStatement {
op: "EDIT"
suffix: string
signal: (string[] | null)
target: (ParsedPath | null)
lineMarker: (LineMarker | null)
body: (string | null)
position: Position
}

export interface CopyStatement {
op: "COPY"
suffix: string
signal: (string[] | null)
target: (ParsedPath | null)
lineMarker: (LineMarker | null)
body: (ResourceSelection | null)
position: Position
}
/**
 * One addressed resource representation and an optional textual region. A fragment-less target selects the scheme's default channel; a URI fragment selects a named channel. The line marker scopes that selected channel.
 */

export interface ResourceSelection {
target: ParsedPath
lineMarker: (LineMarker | null)
}

export interface MoveStatement {
op: "MOVE"
suffix: string
signal: (string[] | null)
target: (ParsedPath | null)
lineMarker: (LineMarker | null)
body: (ResourceSelection | null)
position: Position
}

export interface SendStatement {
op: "SEND"
suffix: string
signal: (number | null)
target: (ParsedPath | null)
lineMarker: (LineMarker | null)
body: (SendBody | null)
position: Position
}
/**
 * Parsed body of a SEND statement. `raw` is the literal body text; `json` is the best-effort `JSON.parse(raw)` result, or null when the body isn't valid JSON.
 */

export interface SendBody {
raw: string
json: unknown
}

export interface ExecStatement {
op: "EXEC"
suffix: string
signal: (string | null)
target: (ParsedPath | null)
lineMarker: (LineMarker | null)
body: (string | null)
position: Position
}

export interface WorkStatement {
op: "WORK"
suffix: string
signal: (string | null)
target: (ParsedPath | null)
lineMarker: null
body: string
position: Position
}

export interface ForkStatement {
op: "FORK"
suffix: string
signal: (string | null)
target: (ParsedPath | null)
lineMarker: null
body: string
position: Position
}

export interface KillStatement {
op: "KILL"
suffix: string
signal: (number | null)
target: (ParsedPath | null)
lineMarker: null
body: (string | null)
position: Position
}

export interface PlanStatement {
op: "PLAN"
suffix: string
signal: (string[] | null)
target: (ParsedPath | null)
lineMarker: (LineMarker | null)
body: (string | null)
position: Position
}

export interface LookStatement {
op: "LOOK"
suffix: string
signal: TagSignal
target: PathOrNull
lineMarker: LineMarkerOrNull
body: MatcherBodyOrNull
position: Position
}

export interface BuffStatement {
op: "BUFF"
suffix: string
signal: TagSignal
target: PathOrNull
lineMarker: LineMarkerOrNull
body: MatcherBodyOrNull
position: Position
}

export interface Notice {
/**
 * Producer identifier. Top-level for self-contained subsystems; colon-namespaced for parameterized producers such as `provider:openai` or `exec:search`.
 */
source: string
/**
 * Open discriminator within a source. Examples include `grammar_unenforced`, `embed_progress`, `search_progress`, and `turn_awaiting_model`.
 */
kind: string
/**
 * Display severity set by the producer. It does not make the Notice a durable operation result.
 */
level: ("error" | "warn" | "info")
/**
 * Optional terse, factual display message.
 */
message?: (string | null)
/**
 * Optional typed position for an observation. ContentOffset points into model output; LogCoordinate points at a durable log row without replacing it.
 */
position?: (ContentOffset | LogCoordinate | null)
[k: string]: unknown
}

export interface ContentOffset {
type: "content-offset"
line: number
column: number
}

export interface LogCoordinate {
type: "log-coordinate"
/**
 * Log row identity, typically `log:///<loop>/<turn>/<sequence>`.
 */
coordinate: string
/**
 * Optional op token (FIND/READ/EDIT/...) at the coordinate, for human-readable rendering.
 */
op?: string
}

export type OperationResult = ({
status: number
problem?: ProblemDetails
error?: never
[k: string]: unknown
} & {
status?: number
})

/**
 * PLURNK operation failure using RFC 9457 Problem Details. Extension members are permitted so an owning boundary can add structured causal and recovery facts without inventing a second error envelope.
 */

export interface ProblemDetails {
/**
 * Absolute URI identifying the stable problem class.
 */
type: string
/**
 * Short, stable summary for this problem type.
 */
title: string
/**
 * Operation status. It must equal the containing result status.
 */
status: number
/**
 * Specific, causal explanation of this occurrence.
 */
detail: string
/**
 * Absolute URI identifying the failed durable operation, normally its log URI. Core adds it at persistence when a plugin cannot know the durable coordinate.
 */
instance?: string
/**
 * Stable producer-owned stage at which the operation failed, when the operation has multiple independently recoverable stages.
 */
stage?: string
/**
 * One generally valid next action. It is omitted when recovery depends on facts the producer does not know.
 */
recovery?: string
/**
 * Whether the producer recommends automatically retrying the identical request.
 */
retryable?: boolean
[k: string]: unknown
}

export type ResourceSelectionOrNull = (ResourceSelection | null)

export type SendBodyOrNull = (SendBody | null)

export interface ProviderDeclaration {
/**
 * API vendor identifier (e.g. "local", "openrouter", "anthropic", "openai").
 */
provider: string
/**
 * Model family (e.g. "gemma", "llama", "qwen", "claude", "gpt", "gemini").
 */
family: string
/**
 * Specific model id (e.g. "gemma3-12b").
 */
model: string
/**
 * Total context window in tokens.
 */
contextSize: number
/**
 * ISO 4217 code for provider cost estimates.
 */
currency: string
}

export interface SchemeRegistration {
/**
 * Scheme name without `://`. Matches the URL scheme character class.
 */
name: string
model_visible: boolean
category: string
default_scope: ("workspace" | "worker")
/**
 * Channel name selected when an op against this scheme has no fragment. Conventionally `body`; executor schemes (`{tag}://`) typically declare `stdout`.
 */
default_channel: string
/**
 * Per-channel content-orientation hints. `head` = whole-document or front-anchored (readers care about the beginning); `tail` = append-temporal stream (readers care about the latest content). Channels not listed default to `head`. Renderers use this to pick truncation direction; the amount to render is a core/runtime concern, not a contract field.
 */
channel_orientations?: {
[k: string]: ("head" | "tail")
}
writable_by: ("model" | "client" | "system" | "plugin")[]
volatile: boolean
handler: (string | null)
}

export interface TextRegion {
startLine: number
startColumn: number
endLine: number
endColumn: number
}
