#!/bin/sh
# chain the operator's global template hook (commitlint) if one exists
if [ -x "$HOME/.git/templates/hooks/commit-msg" ]; then
    exec "$HOME/.git/templates/hooks/commit-msg" "$@"
fi
exit 0
