import { serverProposals } from "./_approval.ts";
import assert from "node:assert/strict";
import test from "node:test";
import { mkdir, readFile, writeFile } from "node:fs/promises";
import { join } from "node:path";
import { Module as McpModule } from "@plurnk/plurnk-mcp";
import { MCP_SCHEMA, PLUGIN_SCHEMA } from "@plurnk/plurnk-agent-plugins";
import { PlurnkParser } from "@plurnk/plurnk-parser";
import type { FunctionalityListResult, PlurnkStatement } from "@plurnk/plurnk-contracts";
import { Mock } from "@plurnk/plurnk-providers";
import Daemon from "../../src/server/Daemon.ts";
import { insertWorker, openMigrated } from "./_db.ts";
import { fixtureExecutors, makeMockResponse, userText } from "./_mock.ts";
import { awaitExecOutcome } from "./_execs.ts";
import { mcpFixture, stdioEntry } from "./_mcp-config.ts";
import { waitFor } from "./_rpc.ts";

const parseOne = (input: string): PlurnkStatement => {
    const item = PlurnkParser.parseStatements(input, { executors: fixtureExecutors(input) }).items.find((item) => item.kind === "statement");
    assert.equal(item?.kind, "statement");
    return item.statement;
};

test("{§mcp-plugin-configuration} workspace management preserves plugin interpretation, restores inheritance, and leaves shared installations intact", { timeout: 30_000 }, async (t) => {
    const { hostPaths, env } = await mcpFixture(t, {});
    const project = join(hostPaths.home, "project");
    const root = join(hostPaths.projectPluginsDir(project), "bundle");
    await mkdir(root, { recursive: true });
    await writeFile(join(root, "plugin.json"), JSON.stringify({ $schema: PLUGIN_SCHEMA, name: "bundle" }));
    const entry = stdioEntry("echo-server.mjs", { PLURNK_MCP_TEST_LAUNCH: "1", SAMPLE: "${PLUGIN_ROOT}", LITERAL: "${VALUE}" });
    const contents = JSON.stringify({ $schema: MCP_SCHEMA, mcpServers: { example: entry } });
    await writeFile(join(root, "mcp.json"), contents);
    env.VALUE = "native-expansion";
    env.PLUGIN_ROOT = "native-root";
    const db = await openMigrated();
    const daemon = new Daemon({ db, provider: null, hostPaths });
    daemon.registerModule(McpModule.init({ env }), "@plurnk/plurnk-mcp");
    t.after(async () => { await daemon.stop(); await db.close(); });
    await daemon.start();
    const a = await daemon.createWorkspace({ name: "plugin-a", projectRoot: project });
    const b = await daemon.createWorkspace({ name: "plugin-b", projectRoot: null });
    const action = (workspaceId: number, verb: string, params = {}) => daemon.invokeModuleAction(`workspace.mcp.${verb}`, params, { scope: "workspace", workspaceId });
    const list = async (workspaceId: number) => (await action(workspaceId, "list") as FunctionalityListResult).definitions;
    assert.deepEqual((await list(a.workspaceId))[0]?.provenance, { kind: "plugin", source: join(root, "mcp.json"), reference: "/mcpServers/example" });
    assert.deepEqual(await list(b.workspaceId), []);
    const call = async () => {
        const before = (await db.test_entries_by_scheme_prefix.all({ workspace_id: a.workspaceId, scheme: "example", prefix: "/%" })).length;
        const result = await daemon.dispatchAsClient({ ...a, statement: parseOne("````example (launch)\n{}\n````") });
        assert.equal(result.status, 200);
        const output = await awaitExecOutcome(db, { workspaceId: a.workspaceId, scheme: "example", channel: "json", after: before });
        return JSON.parse((output.content as { text: string }[])[0]!.text);
    };
    const first = await call();
    assert.equal(first.cwd, root);
    assert.equal(first.root, root);
    assert.equal(first.sample, root);
    assert.equal(first.literal, "${VALUE}");
    assert.equal(first.data, hostPaths.pluginDataDir("bundle", root));
    const marker = join(first.data, "retained.txt");
    await writeFile(marker, "persistent");
    await action(a.workspaceId, "disable", { alias: "example" });
    assert.equal((await list(a.workspaceId))[0]?.state, "disabled");
    await action(a.workspaceId, "enable", { alias: "example" });
    assert.equal((await call()).data, first.data);
    await action(a.workspaceId, "add", { alias: "example", definition: { name: "example", ...entry } });
    const local = await call();
    assert.notEqual(local.cwd, root);
    assert.equal(local.root, undefined, "replacing the definition drops plugin-only environment injection");
    assert.equal(local.sample, "native-root", "native interpretation now owns the identical symbolic value");
    assert.equal(local.literal, "native-expansion");
    await action(a.workspaceId, "remove", { alias: "example" });
    const restored = await call();
    assert.equal(restored.cwd, root);
    assert.equal(restored.literal, "${VALUE}");
    assert.equal(restored.data, first.data);
    assert.equal(await readFile(marker, "utf8"), "persistent");
    assert.equal(await readFile(join(root, "mcp.json"), "utf8"), contents);
});

test("{§mcp-plugin-configuration} unsupported entries reach the model as diagnostics without blocking valid siblings or subsequent repair", { timeout: 30_000 }, async (t) => {
    serverProposals(t, "accept");
    const { hostPaths, env } = await mcpFixture(t, {});
    const project = join(hostPaths.home, "project");
    const root = join(hostPaths.projectPluginsDir(project), "bundle");
    await mkdir(root, { recursive: true });
    await writeFile(join(root, "plugin.json"), JSON.stringify({ $schema: PLUGIN_SCHEMA, name: "bundle" }));
    const entry = stdioEntry("echo-server.mjs");
    const file = join(root, "mcp.json");
    await writeFile(file, JSON.stringify({ $schema: MCP_SCHEMA, mcpServers: { example: entry, legacy: { type: "sse", url: "https://example.org/mcp" } } }));
    const db = await openMigrated();
    const provider = new Mock({ contextWindow: 1_000_000, responses: Array.from({ length: 2 }, () => makeMockResponse("````KILL\nChecked.\n````")) });
    const daemon = new Daemon({ db, provider, hostPaths });
    daemon.registerModule(McpModule.init({ env }), "@plurnk/plurnk-mcp");
    t.after(async () => { await daemon.stop(); await db.close(); });
    const ended: number[] = [];
    t.after(daemon.subscribeToEvents((_w, method, params) => { if (method === "loop/terminated") ended.push((params as { loopId: number }).loopId); }));
    await daemon.start();
    const workspace = await daemon.createWorkspace({ name: "plugin-repair", projectRoot: project });
    const workerId = await insertWorker(db, workspace.workspaceId, null, "model", "model");
    const turn = async () => {
        const started = await daemon.runLoop({ ...workspace, workerId, prompt: "Inspect configuration." });
        await waitFor(() => ended, (ids) => ids.includes(started.loopId), { timeoutMs: 10_000 });
    };
    await turn();
    assert.match(userText(provider.received[0]), /legacy SSE transport is unsupported/);
    const listed = await daemon.invokeModuleAction("workspace.mcp.list", {}, { scope: "workspace", workspaceId: workspace.workspaceId }) as FunctionalityListResult;
    assert.equal(listed.definitions.find(({ alias }) => alias === "example")?.state, "active");
    await writeFile(file, JSON.stringify({ $schema: MCP_SCHEMA, mcpServers: { example: entry } }));
    await turn();
    assert.doesNotMatch(userText(provider.received[1]), /legacy SSE transport is unsupported/);
});
