import test from "node:test";
import assert from "node:assert/strict";
import { mkdir, mkdtemp, readFile, rm, stat, writeFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import { dirname, join } from "node:path";
import HostPaths from "../../src/core/HostPaths.ts";
import WorkspaceStorage from "../../src/server/WorkspaceStorage.ts";
import { insertWorkspace, openMigrated } from "./_db.ts";

test("{§module-workspace-directory} lazy allocation is atomic, rename-stable, durable, and distinct across databases", async (t) => {
    const scratch = await mkdtemp(join(tmpdir(), "plurnk-workspace-storage-"));
    const paths = new HostPaths({ env: {}, home: scratch });
    const databasePath = join(scratch, "first.db");
    let db = await openMigrated(databasePath);
    const otherDb = await openMigrated(join(scratch, "second.db"));
    t.after(async () => { await db.close(); await otherDb.close(); await rm(scratch, { recursive: true, force: true }); });
    const workspaceId = await insertWorkspace(db, "original");
    const otherWorkspaceId = await insertWorkspace(otherDb, "original");
    assert.equal(workspaceId, otherWorkspaceId, "the collision specimen reuses both local id and name");
    const storage = new WorkspaceStorage(db, paths);
    await assert.rejects(stat(paths.stateDir), { code: "ENOENT" }, "constructing the host does not create storage");
    const directories = await Promise.all(Array.from({ length: 16 }, () => storage.directory(workspaceId, "@test/tool")));
    assert.equal(new Set(directories).size, 1);
    const directory = directories[0]!;
    assert.ok(directory.startsWith(`${paths.stateDir}/workspaces/`));
    assert.equal((await stat(directory)).mode & 0o777, 0o700);
    await writeFile(join(directory, "retained.txt"), "tool state");
    await db.envelope_set_workspace_name.get({ id: workspaceId, name: "renamed" });
    assert.equal(await storage.directory(workspaceId, "@test/tool"), directory);
    const sibling = await storage.directory(workspaceId, "../../outside");
    assert.equal(dirname(sibling), dirname(directory), "the module name is one encoded path component");
    assert.notEqual(sibling, directory);
    assert.notEqual(await new WorkspaceStorage(otherDb, paths).directory(otherWorkspaceId, "@test/tool"), directory);
    await db.close();
    db = await openMigrated(databasePath);
    assert.equal(await new WorkspaceStorage(db, paths).directory(workspaceId, "@test/tool"), directory);
    assert.equal(await readFile(join(directory, "retained.txt"), "utf8"), "tool state");
    await db.test_workspaces_delete.run({ id: workspaceId });
    assert.equal(await db.workspace_module_state_get.get({ workspace_id: workspaceId, namespace_owner: "@plurnk/plurnk-service/storage" }), undefined);
    const replacement = await insertWorkspace(db, "renamed");
    assert.notEqual(await new WorkspaceStorage(db, paths).directory(replacement, "@test/tool"), directory);
    assert.equal(await readFile(join(directory, "retained.txt"), "utf8"), "tool state", "deleting a workspace never reassigns or erases its tool state");
});

test("{§module-workspace-directory} missing identities, corrupt keys, and filesystem failures never redirect storage", async (t) => {
    const scratch = await mkdtemp(join(tmpdir(), "plurnk-workspace-storage-invalid-"));
    const paths = new HostPaths({ env: {}, home: scratch });
    const db = await openMigrated();
    t.after(async () => { await db.close(); await rm(scratch, { recursive: true, force: true }); });
    const storage = new WorkspaceStorage(db, paths);
    await assert.rejects(storage.directory(999, "@test/tool"), /Workspace 999 does not exist/);
    const workspaceId = await insertWorkspace(db, "invalid");
    for (const name of ["", ".", ".."]) await assert.rejects(storage.directory(workspaceId, name), /requires a namespace owner/);
    await db.workspace_module_state_put.run({ workspace_id: workspaceId, namespace_owner: "@plurnk/plurnk-service/storage", state: '{"key":"../escape"}' });
    await assert.rejects(storage.directory(workspaceId, "@test/tool"), /invalid storage key/);
    await assert.rejects(storage.upgrade(), /invalid storage key/);
    await assert.rejects(stat(paths.stateDir), { code: "ENOENT" });
    await db.workspace_module_state_delete.run({ workspace_id: workspaceId, namespace_owner: "@plurnk/plurnk-service/storage" });
    await mkdir(dirname(paths.stateDir), { recursive: true });
    await writeFile(paths.stateDir, "occupied");
    await assert.rejects(storage.directory(workspaceId, "@test/tool"), { code: "ENOTDIR" });
});

test("{§skills-storage-upgrade} only this database's directories move; a conflicting destination is never replaced", async (t) => {
    const root = await mkdtemp(join(tmpdir(), "plurnk-storage-upgrade-"));
    const paths = new HostPaths({ env: {}, home: root });
    const db = await openMigrated();
    const otherDb = await openMigrated();
    t.after(async () => { await db.close(); await otherDb.close(); await rm(root, { recursive: true, force: true }); });
    const storage = new WorkspaceStorage(db, paths);
    await storage.upgrade();
    await assert.rejects(stat(paths.stateDir), { code: "ENOENT" }, "upgrading an empty database creates no directories");
    const workspaceId = await insertWorkspace(db, "upgrade");
    const otherId = await insertWorkspace(otherDb, "other");
    const oldOwner = "@plurnk/plurnk-core/skills";
    const owner = "@plurnk/plurnk-skills";
    const previous = await storage.directory(workspaceId, oldOwner);
    const unrelated = await new WorkspaceStorage(otherDb, paths).directory(otherId, oldOwner);
    await writeFile(join(previous, "snapshot"), "pinned copy");
    await writeFile(join(unrelated, "snapshot"), "other database");
    await storage.upgrade();
    const current = await storage.directory(workspaceId, owner);
    assert.equal(await readFile(join(current, "snapshot"), "utf8"), "pinned copy");
    assert.equal(await readFile(join(unrelated, "snapshot"), "utf8"), "other database");
    await assert.rejects(stat(previous), { code: "ENOENT" });
    await storage.upgrade();
    await mkdir(previous);
    await writeFile(join(previous, "snapshot"), "conflicting copy");
    await assert.rejects(storage.upgrade(), /Skills state upgrade cannot replace existing/);
    assert.equal(await readFile(join(current, "snapshot"), "utf8"), "pinned copy");
    assert.equal(await readFile(join(previous, "snapshot"), "utf8"), "conflicting copy");
});
