import { MCP_OAUTH_CLIENT_CREDENTIALS_EXTENSION_ID, MCP_TASKS_EXTENSION_ID } from "./protocol.ts";

export type CapabilityAuthority = "core" | "extension" | "deprecated" | "excluded" | "deferred";
export type CapabilityDisposition = "supported" | "partial" | "excluded" | "deferred";
export type CapabilityAdvertisement = "always" | "conditional" | "never";

export interface CapabilityRow {
    readonly id: string;
    readonly surface: string;
    readonly authority: CapabilityAuthority;
    readonly authorityRef: string;
    readonly advertised: CapabilityAdvertisement;
    readonly interactive: boolean;
    readonly disposition: CapabilityDisposition;
    readonly composed: boolean;
    readonly evidence: readonly string[];
    readonly note: string;
}

// {§mcp-capability-matrix} — the one accountable support matrix. A row is
// "supported" only when every layer its owning contract includes has real
// coverage; advertisement derives from this file, never from ad-hoc claims.
export const CAPABILITY_MATRIX: readonly CapabilityRow[] = [
    {
        id: "base-envelope",
        surface: "JSON-RPC 2.0 base with per-request protocol, identity, and capability metadata; resultType on every result",
        authority: "core",
        authorityRef: "2026-07-28 @ 5f5440bb26a62e2cf3440b92da5a667efa03b267",
        advertised: "never",
        interactive: false,
        disposition: "supported",
        composed: true,
        evidence: ["{§mcp-authority}", "{§mcp-core-matrix}", "plurnk-mcp HttpTransport 'Streamable HTTP carries the current envelope and ordinary tool calls'"],
        note: "Envelope is wire mechanics, not a client capability; preserved without reconstruction.",
    },
    {
        id: "discovery",
        surface: "server/discover probing before registration",
        authority: "core",
        authorityRef: "2026-07-28 @ 5f5440bb26a62e2cf3440b92da5a667efa03b267",
        advertised: "never",
        interactive: false,
        disposition: "supported",
        composed: true,
        evidence: ["{§mcp-authority}", "{§mcp-core-matrix}", "plurnk-core intg 'AG-UI configuration cascade composes MCP discovery, execution, review, failure, and recovery'"],
        note: "Retains identity, instructions, capabilities, versions, and cache hints; modern peers only.",
    },
    {
        id: "tools",
        surface: "tools/list and tools/call",
        authority: "core",
        authorityRef: "2026-07-28 @ 5f5440bb26a62e2cf3440b92da5a667efa03b267",
        advertised: "never",
        interactive: false,
        disposition: "supported",
        composed: true,
        evidence: ["{§mcp-core-matrix}", "{§mcp-tool-presentation}", "plurnk-core intg 'AG-UI configuration cascade composes MCP discovery, execution, review, failure, and recovery'"],
        note: "One operator-filtered exact Registry snapshot; only enabled names are routed.",
    },
    {
        id: "resources",
        surface: "resources/list, resources/templates/list, resources/read",
        authority: "core",
        authorityRef: "2026-07-28 @ 5f5440bb26a62e2cf3440b92da5a667efa03b267",
        advertised: "never",
        interactive: false,
        disposition: "supported",
        composed: true,
        evidence: ["{§mcp-core-matrix}", "{§mcp-model-projection}", "plurnk-mcp McpResources 'resource facet materializes current MCP resources as ordinary entries'"],
        note: "Published through the server's resource authority into Plurnk entries; not a raw client surface.",
    },
    {
        id: "prompts",
        surface: "prompts/list and prompts/get",
        authority: "core",
        authorityRef: "2026-07-28 @ 5f5440bb26a62e2cf3440b92da5a667efa03b267",
        advertised: "never",
        interactive: false,
        disposition: "supported",
        composed: true,
        evidence: ["{§mcp-core-matrix}", "plurnk-mcp McpResources 'prompt definitions and retrieval use the server resource authority'"],
        note: "Prompt definitions and retrieval share the server resource authority.",
    },
    {
        id: "completion",
        surface: "completion/complete for prompts and resource templates",
        authority: "core",
        authorityRef: "2026-07-28 @ 5f5440bb26a62e2cf3440b92da5a667efa03b267",
        advertised: "never",
        interactive: true,
        disposition: "supported",
        composed: true,
        evidence: ["{§mcp-core-matrix}", "{§mcp-management-actions}", "plurnk-mcp client 'client pins the current MCP revision and exercises tools and resources'"],
        note: "Owned by the host interaction that owns the argument; workspace.mcp.complete.",
    },
    {
        id: "pagination",
        surface: "Opaque cursors on list methods",
        authority: "core",
        authorityRef: "2026-07-28 @ 5f5440bb26a62e2cf3440b92da5a667efa03b267",
        advertised: "never",
        interactive: false,
        disposition: "supported",
        composed: false,
        evidence: ["{§mcp-core-matrix}"],
        note: "Finite non-convergence guard; a partial catalog is never published complete.",
    },
    {
        id: "caching",
        surface: "ttlMs and cacheScope on discover, list methods, and resources/read",
        authority: "core",
        authorityRef: "2026-07-28 @ 5f5440bb26a62e2cf3440b92da5a667efa03b267",
        advertised: "never",
        interactive: false,
        disposition: "supported",
        composed: false,
        evidence: ["{§mcp-core-matrix}", "plurnk-mcp subscriptions 'resource reads maintain one overlap-replaced subscription for selected cache entries'"],
        note: "Freshness honored with notification invalidation; private entries partitioned by authorization context.",
    },
    {
        id: "subscriptions",
        surface: "subscriptions/listen with acknowledged filters and correlated notifications",
        authority: "core",
        authorityRef: "2026-07-28 @ 5f5440bb26a62e2cf3440b92da5a667efa03b267",
        advertised: "never",
        interactive: false,
        disposition: "supported",
        composed: true,
        evidence: ["{§mcp-core-matrix}", "plurnk-mcp subscriptions 'a remotely ended unified subscription is re-established with a fresh request'"],
        note: "One current filter for list changes, cached resource URIs, and active Task IDs; overlap replacement and re-listen after loss.",
    },
    {
        id: "progress",
        surface: "Request-scoped notifications/progress",
        authority: "core",
        authorityRef: "2026-07-28 @ 5f5440bb26a62e2cf3440b92da5a667efa03b267",
        advertised: "never",
        interactive: false,
        disposition: "supported",
        composed: true,
        evidence: ["{§mcp-core-matrix}", "plurnk-mcp McpExecutor 'MCP progress and cancellation remain on the owning EXEC lifecycle over stdio'"],
        note: "Projected onto the owning Plurnk operation; no independent protocol lifecycle.",
    },
    {
        id: "cancellation",
        surface: "Stream closure on HTTP; notifications/cancelled on stdio",
        authority: "core",
        authorityRef: "2026-07-28 @ 5f5440bb26a62e2cf3440b92da5a667efa03b267",
        advertised: "never",
        interactive: false,
        disposition: "supported",
        composed: true,
        evidence: ["{§mcp-core-matrix}", "plurnk-mcp HttpTransport 'HTTP progress and stream cancellation settle the same request'"],
        note: "Driven from the owning Plurnk abort signal; settles the same operation.",
    },
    {
        id: "mrtr",
        surface: "input_required on tools/call, resources/read, or prompts/get",
        authority: "core",
        authorityRef: "2026-07-28 @ 5f5440bb26a62e2cf3440b92da5a667efa03b267",
        advertised: "never",
        interactive: true,
        disposition: "supported",
        composed: true,
        evidence: ["{§mcp-core-matrix}", "plurnk-mcp Module 'one input_required round becomes one atomic client interaction'", "plurnk-core intg ClientInteractions"],
        note: "Opaque requestState echoed byte-for-byte; only the originating request retried with a fresh ID.",
    },
    {
        id: "elicitation",
        surface: "Elicitation through MRTR with form and URL modes",
        authority: "core",
        authorityRef: "2026-07-28 @ 5f5440bb26a62e2cf3440b92da5a667efa03b267",
        advertised: "always",
        interactive: true,
        disposition: "supported",
        composed: true,
        evidence: ["{§mcp-core-matrix}", "plurnk-mcp Module 'form and URL responses are validated before retrying the origin'", "plurnk-agui AguiPlus 'client interaction projects its exact tool call, interrupt guidance, and response schema'", "plurnk TUI question tool (plurnk repo)", "plurnk.nvim lua/plurnk/question.lua (plurnk.nvim repo)"],
        note: "Modes form and url advertised; routed through Plurnk's client-owned interaction lifecycle.",
    },
    {
        id: "authorization-bearer",
        surface: "Static bearer token over HTTP",
        authority: "core",
        authorityRef: "2026-07-28 @ 5f5440bb26a62e2cf3440b92da5a667efa03b267",
        advertised: "never",
        interactive: false,
        disposition: "supported",
        composed: false,
        evidence: ["{§mcp-configuration}", "plurnk-mcp HttpTransport 'HTTP bearer credentials expand only while preparing a connection'"],
        note: "Private-service/legacy transport credential; one complete environment reference.",
    },
    {
        id: "authorization-oauth",
        surface: "Interactive OAuth over HTTP",
        authority: "core",
        authorityRef: "2026-07-28 @ 5f5440bb26a62e2cf3440b92da5a667efa03b267",
        advertised: "never",
        interactive: true,
        disposition: "supported",
        composed: true,
        evidence: ["{§mcp-management-actions}", "{§oauth-lifetime}", "plurnk-mcp HttpTransport 'interactive HTTP OAuth preserves discovery, PKCE, state, issuer, and resource binding'"],
        note: "Human principals via workspace attachments; validated metadata, PKCE, issuer, resource indicators, refresh, bounded scope.",
    },
    {
        id: MCP_TASKS_EXTENSION_ID,
        surface: "Tasks extension: task creation, polling, input, cancellation, notifications, terminal settlement",
        authority: "extension",
        authorityRef: "experimental-ext-tasks @ 2c1425d9a288b9b1f489430fe1e00bb392b47e48",
        advertised: "always",
        interactive: true,
        disposition: "supported",
        composed: true,
        evidence: ["{§mcp-tasks}", "plurnk-mcp Tasks 'current HTTP Tasks preserve MRTR, task input, polling, notifications, and routing'", "plurnk-core intg ClientInteractions", "plurnk-agui AguiPlus 'client interaction projects its exact tool call, interrupt guidance, and response schema'"],
        note: "Advertised only when the complete in-process lifecycle is active; never core conformance. Task input routes through the general interaction owner.",
    },
    {
        id: MCP_OAUTH_CLIENT_CREDENTIALS_EXTENSION_ID,
        surface: "oauth-client-credentials extension, client-secret arm",
        authority: "extension",
        authorityRef: "official extension; secret-only client permitted by the contract",
        advertised: "conditional",
        interactive: false,
        disposition: "supported",
        composed: false,
        evidence: ["{§oauth-client-credentials}", "plurnk-mcp HttpTransport '{§oauth-client-credentials} the extension capability is advertised only on client-credentials connections'"],
        note: "Application principals; advertised only on connections holding a client-credentials definition; issuer binding; JWT arms declined.",
    },
    {
        id: "extension-roots",
        surface: "Roots",
        authority: "deprecated",
        authorityRef: "2026-07-28 @ 5f5440bb26a62e2cf3440b92da5a667efa03b267",
        advertised: "never",
        interactive: false,
        disposition: "excluded",
        composed: false,
        evidence: ["{§mcp-exclusions}"],
        note: "Explicit resources/tool arguments instead.",
    },
    {
        id: "extension-sampling",
        surface: "Sampling",
        authority: "deprecated",
        authorityRef: "2026-07-28 @ 5f5440bb26a62e2cf3440b92da5a667efa03b267",
        advertised: "never",
        interactive: false,
        disposition: "excluded",
        composed: false,
        evidence: ["{§mcp-exclusions}"],
        note: "Plurnk's provider layer owns model access.",
    },
    {
        id: "extension-logging",
        surface: "Logging",
        authority: "deprecated",
        authorityRef: "2026-07-28 @ 5f5440bb26a62e2cf3440b92da5a667efa03b267",
        advertised: "never",
        interactive: false,
        disposition: "excluded",
        composed: false,
        evidence: ["{§mcp-exclusions}"],
        note: "stderr/OpenTelemetry instead.",
    },
    {
        id: "transport-http-sse",
        surface: "HTTP+SSE transport",
        authority: "deprecated",
        authorityRef: "2026-07-28 @ 5f5440bb26a62e2cf3440b92da5a667efa03b267",
        advertised: "never",
        interactive: false,
        disposition: "excluded",
        composed: false,
        evidence: ["{§mcp-exclusions}"],
        note: "Streamable HTTP only.",
    },
    {
        id: "oauth-dcr",
        surface: "OAuth Dynamic Client Registration",
        authority: "deprecated",
        authorityRef: "2026-07-28 @ 5f5440bb26a62e2cf3440b92da5a667efa03b267",
        advertised: "never",
        interactive: false,
        disposition: "excluded",
        composed: false,
        evidence: ["{§mcp-exclusions}", "plurnk-mcp HttpTransport '{§mcp-exclusions} unavailable deprecated DCR is attributed without probing it'"],
        note: "Pre-registration, then CIMD; DCR only via advertised registration_endpoint.",
    },
    {
        id: "legacy-lifecycle",
        surface: "initialize, notifications/initialized, Mcp-Session-Id, HTTP GET event stream, ping, logging/setLevel, roots list_changed",
        authority: "excluded",
        authorityRef: "2026-07-28 @ 5f5440bb26a62e2cf3440b92da5a667efa03b267",
        advertised: "never",
        interactive: false,
        disposition: "excluded",
        composed: false,
        evidence: ["{§mcp-exclusions}"],
        note: "Removed; every request is stateless and self-contained.",
    },
    {
        id: "legacy-subscriptions",
        surface: "resources/subscribe, resources/unsubscribe, SSE resumption, Last-Event-ID",
        authority: "excluded",
        authorityRef: "2026-07-28 @ 5f5440bb26a62e2cf3440b92da5a667efa03b267",
        advertised: "never",
        interactive: false,
        disposition: "excluded",
        composed: false,
        evidence: ["{§mcp-exclusions}"],
        note: "Removed; subscriptions/listen and fresh request IDs instead.",
    },
    {
        id: "legacy-tasks",
        surface: "Legacy Tasks tasks/list, tasks/result, task-augmentation request fields",
        authority: "excluded",
        authorityRef: "experimental-ext-tasks @ 2c1425d9a288b9b1f489430fe1e00bb392b47e48",
        advertised: "never",
        interactive: false,
        disposition: "excluded",
        composed: false,
        evidence: ["{§mcp-exclusions}"],
        note: "Removed; only the negotiated final Tasks extension.",
    },
    {
        id: "extension-cc-jwt",
        surface: "oauth-client-credentials JWT and private-key assertion arms",
        authority: "extension",
        authorityRef: "official extension; the contract permits a secret-only client",
        advertised: "never",
        interactive: false,
        disposition: "excluded",
        composed: false,
        evidence: ["{§oauth-client-credentials}"],
        note: "Declared non-goal; secret-only client.",
    },
    {
        id: "extension-ema",
        surface: "Enterprise-managed authorization",
        authority: "extension",
        authorityRef: "official extension; org-owned identity",
        advertised: "never",
        interactive: false,
        disposition: "deferred",
        composed: false,
        evidence: ["https://repo.possumtech.com/plurnk/plurnk-service/issues/270"],
        note: "Deferred to #270; requires the public host seam decision.",
    },
    {
        id: "extension-dpop",
        surface: "DPoP proofs",
        authority: "extension",
        authorityRef: "official extension",
        advertised: "never",
        interactive: false,
        disposition: "deferred",
        composed: false,
        evidence: [],
        note: "Not required by any adopted arm; revisit with enterprise-managed authorization.",
    },
    {
        id: "extension-wif-jwt-bearer",
        surface: "WIF JWT bearer grant",
        authority: "extension",
        authorityRef: "official extension",
        advertised: "never",
        interactive: false,
        disposition: "deferred",
        composed: false,
        evidence: ["https://repo.possumtech.com/plurnk/plurnk-service/issues/270"],
        note: "Org-owned identity territory; deferred with enterprise-managed authorization.",
    },
];

export const ADVERTISED_ELICITATION_MODES = ["form", "url"] as const;

export const CONDITIONAL_EXTENSION_IDS: readonly string[] = CAPABILITY_MATRIX
    .filter((row) => row.advertised === "conditional")
    .map((row) => row.id);

// {§mcp-capability-matrix} — advertisement derives from the matrix by
// construction; an extension is on the wire only because a row says "always".
export const staticClientCapabilities = (): {
    readonly elicitation: Record<(typeof ADVERTISED_ELICITATION_MODES)[number], Record<string, never>>;
    readonly extensions: Record<string, Record<string, never>>;
} => ({
    elicitation: Object.fromEntries(
        ADVERTISED_ELICITATION_MODES.map((mode) => [mode, {}]),
    ) as never,
    extensions: Object.fromEntries(
        CAPABILITY_MATRIX
            .filter((row) => row.authority === "extension" && row.advertised === "always")
            .map((row) => [row.id, {}]),
    ),
});
