import { readFile, writeFile, readdir } from "node:fs/promises";
import { join, basename } from "node:path";
import { compile } from "json-schema-to-typescript";

const SCHEMA_DIR = "schema";
const OUTPUT_FILE = "src/types.generated.ts";

const httpsResolver = {
    https: {
        canRead: /^https:\/\/schemas\.plurnk\.xyz\//,
        async read({ url }: { url: string }): Promise<unknown> {
            const filename = basename(new URL(url).pathname);
            return JSON.parse(await readFile(join(SCHEMA_DIR, filename), "utf8"));
        },
    },
};

const files = (await readdir(SCHEMA_DIR))
    .filter((file) => file.endsWith(".json"))
    .sort();
const emitted = new Set<string>();
const declaration = /^export (?:interface|type) (\w+)/m;
let combined = [
    "// @generated by scriptify/generate-types.ts from schema/*.json",
    "// DO NOT EDIT — run `npm run build:types` to regenerate.",
    "",
    "",
].join("\n");

for (const file of files) {
    const name = file.replace(/\.json$/, "");
    const schema = JSON.parse(await readFile(join(SCHEMA_DIR, file), "utf8"));
    const source = await compile(schema, name, {
        bannerComment: "",
        $refOptions: {
            resolve: {
                http: false,
                ...httpsResolver,
            } as never,
        },
        declareExternallyReferenced: true,
        additionalProperties: false,
        format: false,
        style: { singleQuote: false, useTabs: false, tabWidth: 4 },
    });
    const normalized = source.replace(/[ \t]+$/gm, "");
    for (const block of normalized.split(/\n(?=export (?:interface|type) )/)) {
        const match = declaration.exec(block);
        if (match === null || emitted.has(match[1])) continue;
        emitted.add(match[1]);
        combined += `${block.trimEnd()}\n\n`;
    }
}

await writeFile(OUTPUT_FILE, `${combined.trimEnd()}\n`);
process.stderr.write(`Generated ${OUTPUT_FILE}: ${emitted.size} types from ${files.length} schemas.\n`);
