// CHANGELOG.md is generated from conventional commit subjects between release tags and is
// never edited by hand. `--write` regenerates it, `--check` fails when the file differs from
// the generated text (the root lint runs it, so a tag without a regenerated changelog fails
// the next push), and `--pending` prints the notes accumulated since the last tag.
import { execFile } from "node:child_process";
import { readFile, writeFile } from "node:fs/promises";
import path from "node:path";
import { parseArgs, promisify } from "node:util";

const run = promisify(execFile);
const root = path.resolve(import.meta.dirname, "..");
const FILE = path.join(root, "CHANGELOG.md");
const SUBJECT = /^([a-z]+)(?:\(([a-z0-9-]+)\))?(!?): (.+)$/;
const SECTIONS = [
    ["feat", "Features"],
    ["fix", "Fixes"],
    ["perf", "Performance"],
    ["refactor", "Refactors"],
    ["docs", "Documentation"],
    ["revert", "Reverts"],
];
const HEADER = `# Changelog

Generated by \`scripts/changelog.mjs\` from commit subjects between release tags.
Chores, tests, builds, and tooling commits are omitted. Regenerate with
\`npm run changelog -- --write\`; \`npm run changelog\` prints what is pending.
`;

const git = async (...args) => (await run("git", args, { cwd: root, maxBuffer: 64 * 1024 * 1024 })).stdout;

const tags = async () => (await git("tag", "--list", "v*", "--sort=creatordate")).trim().split("\n").filter(Boolean);

const subjects = async (range) => (await git("log", "--format=%s", "--no-merges", range)).split("\n").filter(Boolean);

const entries = (lines) => {
    const groups = new Map(SECTIONS.map(([type]) => [type, []]));
    const breaking = [];
    for (const line of lines) {
        const m = SUBJECT.exec(line);
        if (m === null) continue;
        const [, type, scope, bang, rest] = m;
        // A subject may name a SPEC tag with its sign; the changelog is prose, so the sign goes.
        const text = (scope === undefined ? rest : `${scope}: ${rest}`).replaceAll("§", "");
        if (bang === "!") breaking.push(text);
        else if (groups.has(type)) groups.get(type).push(text);
    }
    return { breaking, groups };
};

const section = (title, date, lines) => {
    const { breaking, groups } = entries(lines);
    const out = [`## ${title}${date === null ? "" : ` — ${date}`}`, ""];
    const block = (name, items) => { if (items.length === 0) return; out.push(`${name}:`, "", ...items.map((item) => `- ${item}`), ""); };
    block("Breaking", breaking);
    for (const [type, name] of SECTIONS) block(name, groups.get(type));
    if (out.length === 2) out.push("No itemized changes.", "");
    return out.join("\n");
};

export const releaseNotes = async (cwd, tag, repo) => {
    const readGit = async (...args) => (await run("git", args, { cwd, maxBuffer: 64 * 1024 * 1024 })).stdout.trim();
    const list = (await readGit("tag", "--merged", tag, "--list", "v*", "--sort=creatordate")).split("\n");
    const index = list.indexOf(tag);
    if (index < 0) throw new Error(`release tag ${tag} is missing`);
    const range = index === 0 ? tag : `${list[index - 1]}..${tag}`;
    const lines = (await readGit("log", "--format=%s", "--no-merges", range)).split("\n");
    return section(tag.slice(1), null, lines).replace(
        /(?<![\w/])#(\d+)\b/g,
        (_, number) => `[#${number}](https://repo.possumtech.com/plurnk/${repo}/issues/${number})`,
    );
};

const generate = async () => {
    const list = await tags();
    const parts = [HEADER];
    for (let i = list.length - 1; i >= 0; i -= 1) {
        const tag = list[i];
        const date = (await git("log", "-1", "--format=%ad", "--date=short", tag)).trim();
        const range = i === 0 ? tag : `${list[i - 1]}..${tag}`;
        const lines = i === 0 ? [] : await subjects(range);
        parts.push(i === 0 ? `## ${tag.slice(1)} — ${date}\n\nFirst tagged release.\n` : section(tag.slice(1), date, lines));
    }
    return parts.join("\n");
};

if (import.meta.main) {
    const { values } = parseArgs({ options: { write: { type: "boolean", default: false }, check: { type: "boolean", default: false } } });
    if (values.write) {
        await writeFile(FILE, await generate());
        console.log("CHANGELOG.md regenerated");
    } else if (values.check) {
        const expected = await generate();
        const actual = await readFile(FILE, "utf8");
        if (actual !== expected) {
            process.stderr.write("CHANGELOG.md differs from the text generated from the release tags; run `npm run changelog -- --write` and commit it\n");
            process.exit(1);
        }
        console.log("changelog OK: matches the release tags");
    } else {
        const list = await tags();
        const last = list.at(-1);
        process.stdout.write(section(`Pending since ${last}`, null, await subjects(`${last}..HEAD`)));
    }
}
