import assert from "node:assert/strict";
import test from "node:test";
import GeneratedByteSource from "./GeneratedByteSource.ts";

test("{§scheme-source-bytes} generated bytes are lazy, consistent, and have no fabricated file", async () => {
    let calls = 0;
    const source = new GeneratedByteSource(async () => {
        calls++;
        return Uint8Array.of(0, 255, 128, 65);
    });
    assert.equal(calls, 0);
    assert.equal("nativePath" in source, false);
    assert.equal(await source.size(), 4);
    assert.deepEqual(await source.read(2, 3), Uint8Array.of(255, 128));
    assert.deepEqual(await source.read(4, 8), Uint8Array.of(65));
    assert.deepEqual(await source.read(1, 0), new Uint8Array());
    assert.equal(calls, 1);
});

test("{§scheme-source-bytes} generated absence and generation failures remain distinct", async () => {
    const absent = new GeneratedByteSource(async () => null);
    assert.equal(await absent.size(), null);
    await assert.rejects(absent.read(1, 1), /no longer exists/);
    const failure = new Error("catalog generation failed");
    const broken = new GeneratedByteSource(async () => { throw failure; });
    await assert.rejects(broken.size(), (cause) => cause === failure);
    await assert.rejects(broken.read(1, 1), (cause) => cause === failure);
});
