import { readFile, writeFile, readdir } from "node:fs/promises";
import { join, basename } from "node:path";
import { compile } from "json-schema-to-typescript";

const SCHEMA_DIR = "schema";
const OUTPUT_FILE = "src/types.generated.ts";

// Resolve cross-schema $refs that use the canonical `https://schemas.plurnk.dev/v0/*.json`
// URI by reading the corresponding local file.
const httpsResolver = {
    https: {
        canRead: /^https:\/\/schemas\.plurnk\.dev\//,
        async read({ url }: { url: string }): Promise<unknown> {
            const filename = basename(new URL(url).pathname);
            return JSON.parse(await readFile(join(SCHEMA_DIR, filename), "utf8"));
        },
    },
};

const files = (await readdir(SCHEMA_DIR))
    .filter((f) => f.endsWith(".json"))
    .sort();

const banner = [
    "// @generated by scriptify/generate-types.ts from schema/*.json",
    "// DO NOT EDIT — run `npm run build:types` to regenerate.",
    "",
    "",
].join("\n");

// Each top-level compile emits both the named type and any referenced types
// (internal $defs and cross-file $refs). Cross-file refs duplicate across compiles;
// we keep only the first occurrence of each declaration name.
const emitted = new Set<string>();
const declHeader = /^export (?:interface|type) (\w+)/m;
let combined = banner;

for (const file of files) {
    const name = file.replace(/\.json$/, "");
    const schemaText = await readFile(join(SCHEMA_DIR, file), "utf8");
    const schema = JSON.parse(schemaText);
    const ts = await compile(schema, name, {
        bannerComment: "",
        $refOptions: { resolve: httpsResolver as never },
        declareExternallyReferenced: true,
        additionalProperties: false,
        format: false,
        style: { singleQuote: false, useTabs: false, tabWidth: 4 },
    });
    const blocks = ts.split(/\n(?=export (?:interface|type) )/);
    for (const block of blocks) {
        const match = declHeader.exec(block);
        if (!match) continue;
        const typeName = match[1];
        if (emitted.has(typeName)) continue;
        emitted.add(typeName);
        combined += block.trimEnd() + "\n\n";
    }
}

await writeFile(OUTPUT_FILE, combined.trimEnd() + "\n");
process.stdout.write(`Generated ${OUTPUT_FILE}: ${emitted.size} types from ${files.length} schemas.\n`);
